### ISSUE TITLE
XmippTomoScoreCoordinates test not passing

### ISSUE THREAD

**Issue by fede-pe** [I2PC/scipion-em-xmipptomo#107]
XmippTomoScoreCoordinates test not passing because deep micrograph cleaner is not found. Tested in two different machines, devel branches, new compilation, same error. 

/bin/sh: 1: xmipp_deep_micrograph_cleaner: not found
Traceback (most recent call last):
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 201, in run
    self._run()
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 252, in _run
    resultFiles = self._runFunc()
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 248, in _runFunc
    return self._func(*self._args)
  File "/home/fdeisidro/scipion3/Plugins/scipion-em-xmipptomo/xmipptomo/protocols/protocol_score_coordinates.py", line 129, in detectCarbonCloseness
    self.runJob('xmipp_deep_micrograph_cleaner', args, env=Plugin.getTensorFlowEnviron())
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1483, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 65, in runJob
    process.runJob(log, programName, params,
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/utils/process.py", line 55, in runJob
    return runCommand(command, env, cwd)
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/fdeisidro/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' xmipp_deep_micrograph_cleaner -i Runs/000119_XmippProtScoreCoordinates/tmp/inputTomo.xmd -c Runs/000119_XmippProtScoreCoordinates/extra/inputCoords -o Runs/000119_XmippProtScoreCoordinates/extra/outputCoords -b 32' returned non-zero exit status 127.
Protocol failed: Command ' xmipp_deep_micrograph_cleaner -i Runs/000119_XmippProtScoreCoordinates/tmp/inputTomo.xmd -c Runs/000119_XmippProtScoreCoordinates/extra/inputCoords -o Runs/000119_XmippProtScoreCoordinates/extra/outputCoords -b 32' returned non-zero exit status 127.

*************** end of STD ERR *********************

[   FAILED ] XmippTomoScoreCoordinates.test_score_coordinates

Traceback (most recent call last):
  File "/home/fdeisidro/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/fdeisidro/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/fdeisidro/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/fdeisidro/scipion3/Plugins/scipion-em-xmipptomo/xmipptomo/tests/test_protocols_xmipptomo.py", line 315, in test_score_coordinates
    filteredCoords = self._createProtScoreCarbon(protCoords)
  File "/home/fdeisidro/scipion3/Plugins/scipion-em-xmipptomo/xmipptomo/tests/test_protocols_xmipptomo.py", line 297, in _createProtScoreCarbon
    self.launchProtocol(protScoreCoordinates)
  File "/home/fdeisidro/scipion3/scipion-pyworkflow/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol Filter Carbon - Threshold 0.8 execution failed. See last log lines above for more details.

[==========] run 1 tests (5.755 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests

**Comment by fede-pe** [comment]
An update to this issue.

Test passing in two (ubuntu) local machines. Not passing either in buildbot or hrtz-dos (centOS). The environment under which this protocol is executed (xmipp_MicCleaner). One possible error is 

[No module named 'numpy.core._multiarray_umath'](https://stackoverflow.com/questions/54665842/when-importing-tensorflow-i-get-the-following-error-no-module-named-numpy-cor)

It is reported that this error appears for some configurations with numpy 1.15.4 (the one defined in the environment). Upgrading to >1.16.1 fix this issue but new problems appear. Probably a better definition of the environment is needed.

I keep it open since this is still an issue.
